name: Python application

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create .env
      run: |
        touch .env
        echo echo user=${{ secrets.user }} >> .env
        echo echo password=${{ secrets.password }} >> .env
        echo echo host=${{ secrets.host }} >> .env
        echo echo port=${{ secrets.port }} >> .env
        echo echo dbname=${{ secrets.dbname }} >> .env
        echo echo sender_mail=${{ secrets.sender_mail }} >> .env
        echo echo sender_password=${{ secrets.sender_password }} >> .env

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate ssl and build
      run: |
        python ssl_gen.py
        python app.py
