name: Python application

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Create .env
      run: |
        touch .env
        echo user=${{ secrets.USER }} >> .env
        echo password=${{ secrets.PASSWORD }} >> .env
        echo host=${{ secrets.HOST }} >> .env
        echo port=${{ secrets.PORT }} >> .env
        echo dbname=${{ secrets.DBNAME }} >> .env
        echo sender_mail=${{ secrets.SENDER_MAIL }} >> .env
        echo sender_password=${{ secrets.SENDER_PASSWORD }} >> .env

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate ssl
      run: |
        python ssl_gen.py

    - name: Run Flask in Background (with logging)
      run: |
        python app.py
